### ISSUE TITLE
High CPU Usage and DPR not displaying.

### ISSUE THREAD

**Issue by TheRewinderCC** [Minibeast/LiveSplit.Discord#3]
The Rich Presence doesn't appear and when I start the timer (with the component installed; I installed the component correctly and made sure of it.) it eats CPU; without the component, the CPU usage lingers around 2% - 4%, but with the component installed it uses 7% - 10%.

**Comment by TheRewinderCC** [comment]
(The CPU usage is with the timer running btw)

**Comment by amyy54** [comment]
Interesting. I don't think I've ever had CPU issues when using the component. If possible, could you show me the error that appears in event viewer (if one appears at all).
