### ISSUE TITLE
Timer appears to run slowly and autosplitter doesn't split/remove loads on v1.6.0

### ISSUE THREAD

**Issue by haz429** [Minibeast/LiveSplit.Discord#4]
On previous versions up until v1.5.7, this component works perfectly for me, however the latest update is effectively broken for me. 

The decimals on my timer look a lot less smoother than usual, and more importantly, the autosplitter I'm using (for The Simpsons: Hit & Run) does not remove load times, or split after a completed mission (but does start automatically). The autosplitter settings also disappear (usually looks like this: https://i.imgur.com/2NA4ZV5.png, but with v.1.6.0 it is completely blank: https://i.imgur.com/sBPWtu1.png).

Please let me know if I can do anything/provide any specs in helping fix this issue.

Thanks! 😄

**Comment by Minibeast** [comment]
Hmm, interesting. I haven't seen any issues with the Timer caused by LiveSplit.Discord, and using the autosplitter for The Simpsons Hit & Run seemingly works on my LiveSplit (the menus all show correctly like it does in your first screenshot). Is it possible that something else modified LiveSplit directly? I would suggest doing a full reinstall of LiveSplit and seeing if the issues are still present, and testing to see if LiveSplit.Discord is directly causing the issues (I can't see any reason for LiveSplit.Discord to cause those problems due to how LiveSplit components are designed).

**Comment by haz429** [comment]
I can confirm that with a fresh install of LiveSplit, the newest version of LiveSplit.Discord is causing the issues. Removing the component from my layout or using v.1.5.7 removes these issues and the timer/autosplitter works as intended in both my main LiveSplit installation and the new one I had just made.

The autosplitter settings disappearing seems to be fixed on my 2nd LiveSplit installation, but the same issues still occur.

**Comment by Minibeast** [comment]
If Discord is completely closed and LiveSplit is relaunched, do the issues still present themselves?

If possible could you check Windows Event Viewer to see if any errors are being displayed, and if so what are the error messages?

**Comment by haz429** [comment]
When Discord is completely closed, it reopens automatically when LiveSplit is opened (which I'm assuming is intended), and I have to run LiveSplit.exe a second time for LiveSplit to actually open - doing this did not fix the issue.

Whilst the timer is running and LiveSplit.Discord v.1.6.0 is on my layout, the following error is spammed on Event Viewer around 14-15 times per second:

> Nullable object must have a value.
> 
>    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
>    at LiveSplit.UI.Components.DiscordComponent.<UpdatePresence>g__CheckText|19_2(String item, <>c__DisplayClass19_0& )
>    at LiveSplit.UI.Components.DiscordComponent.UpdatePresence(LiveSplitState state)
>    at LiveSplit.UI.Components.DiscordComponent.Update(IInvalidator invalidator, LiveSplitState state, Single width, Single height, LayoutMode mode)
>    at LiveSplit.UI.Components.ComponentRenderer.InvalidateVerticalComponent(Int32 index, LiveSplitState state, IInvalidator invalidator, Single width, Single height, Single scaleFactor)
>    at LiveSplit.UI.Components.ComponentRenderer.Update(IInvalidator invalidator, LiveSplitState state, Single width, Single height, LayoutMode mode)
>    at LiveSplit.View.TimerForm.<TimerElapsed>b__185_1()

Hope this helps.

**Comment by Minibeast** [comment]
Could you screenshot the settings you're currently using for LiveSplit.Discord?

(The best way to do this is to screenshot the settings in the layout file)

**Comment by haz429** [comment]
As far as I'm aware, the settings are default (I would probably change a few settings so it would look like this when it is working, but these issues happen regardless: https://i.imgur.com/lPkHQdl.png)

![LiveSplit_N0bNklBFY9](https://user-images.githubusercontent.com/4999264/119233583-b92d4a00-bb21-11eb-9afc-7c2e51fd6e49.png)

**Comment by Minibeast** [comment]
And just to check: this happens with every split file?

If it only happens with one or two specific split files please send them over.

**Comment by haz429** [comment]
Okay so I've done some more testing, and by the looks of it, the problem doesnt exist with a fresh splits file with a few splits and only the first few autosplitter settings ticked. However, when I ticked the normal amount of autosplitter settings, and added more splits, the issue got worse and worse, and eventually the same as initially reported. Changing that same file back to a few splits and a few autosplitter settings ticked, and the issue was minor with a late timer start (timer usually starts at 40.9 in this game, it would start at around 41.2 in this case, I guess just being slow to remove the load) but loads being removed and splitting after missions.

So pretty much, the bigger the splits file, the worse the issue gets.

**Comment by Minibeast** [comment]
If the autosplitter is completely turned off does having a large splits file still cause issues?

**Comment by haz429** [comment]
With the autosplitter deactivated, the timer still looks a lot less smoother with LiveSplit.Discord v1.6.0 compared to without the component. The error is also still spammed in Event Viewer with the autosplitter deactivated.

**Comment by Minibeast** [comment]
Okay, thanks for letting me know. I am unsure what the problem is directly as having a large amount of splits hasn't impacted my usage of the component. However, I will try to figure out the issue based on the things you've provided. For now, if v1.5.7 works perfectly fine, you can continue using that.

**Comment by Minibeast** [comment]
Hello, based on the error message provided I modified part of the program that was reportedly having issues. Whenever you get the chance could you try the component linked below and see if that solves the problem? If it does I'll push the changes into a more official release. 

https://drive.google.com/file/d/1owIx1ikC3CY3eZ7Hmtj9sxQd482iRBB6/view?usp=sharing

**Comment by haz429** [comment]
Hey there, I can confirm that the linked component has fixed the issue, and the timer/autosplitter works flawlessly now. Thank you so much for looking into it and fixing it, will be good to use the new features of v1.6.0 😄

**Comment by Minibeast** [comment]
Perfect! I'll make an official release later tonight with the changes that solves the issues you were experiencing.
